pub mod audio;
pub mod battery;
pub mod clipboard_store;
pub mod compositor;
pub mod extension_protocol;
pub mod local_ai;
pub mod media;
pub mod network;
pub mod notifications;
#[cfg(feature = "gui")]
pub mod poll_cache;
pub mod storage;
pub mod system_stats;
pub mod terminal;
pub mod text_input;
pub mod thermal;
